var fullName = 'Lisa Nguyen';
var isCool = true;
var totalPets = 2;
var unknown = null;
let never;
console.log('value of FullName', fullName);
console.log('value of isCool', isCool);
console.log('value of totalPets', totalPets);
console.log('typeof fullName', typeof fullName);
console.log('typeof isCool', typeof isCool);
console.log('typeof totalPets', typeof totalPets);
console.log('value of', unknown);
console.log('typeof unknown', typeof unknown);
console.log('value of never', never);
console.log('typeof never', typeof never);
